# Generated by Django 4.0.1 on 2022-02-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.TextField(max_length=70)),
                ('stuemail', models.EmailField(max_length=70)),
                ('stupass', models.TextField(max_length=70)),
            ],
        ),
    ]
