# Generated by Django 4.0.1 on 2022-02-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gallery_galleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='title',
            new_name='name',
        ),
    ]
