# Generated by Django 4.0.1 on 2022-02-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subplan_subplanfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subplanfeature',
            old_name='title',
            new_name='name',
        ),
    ]
