# Generated by Django 4.0.1 on 2022-02-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_title_subplanfeature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplan',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='SubPlan',
        ),
        migrations.DeleteModel(
            name='SubPlanFeature',
        ),
    ]
